[package]
name = "baker_layer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
baker_layer_pb = { path = "../baker_layer_pb" }
prost = "0.8"
which = "4.2.2"
